security:
    enable_authenticator_manager: true
    encoders:
        App\Entity\User:
            algorithm: auto
        App\Entity\Admin:
            algorithm: auto
    providers:
        user:
            entity: { class: App\Entity\User, property: email }
        admin:
            entity: { class: App\Entity\Admin, property: username }
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        login:
            pattern: ^/api/login
            provider: user
            stateless: true
            json_login:
                check_path: /api/login_check
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure


        main:
            pattern: ^/
            provider: user
            logout:
                invalidate_session: true
                path: /logout
                target: /

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/profile, roles: ROLE_USER }
        - { path: ^/_easyadmin/login, role: ROLE_ADMIN }
        - { path: ^/_easyadmin, role: ROLE_ADMIN }
        - { path: ^/admin, role: ROLE_ADMIN }
        - { path: ^/account, roles: ROLE_ADMIN }
        - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
