monolog:
    handlers:
        main:
            type: rotating_file
            max_files: 20
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            action_level: error
            channels: ["!event"]
            buffer_size: 50
            #excluded_http_codes: [404, 405]
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]

        # Uncomment to log deprecations
        #deprecation:
        #    type: stream
        #    path: "%kernel.logs_dir%/%kernel.environment%.deprecations.log"
        #deprecation_filter:
        #    type: filter
        #    handler: deprecation
        #    max_level: info
        #    channels: ["php"]
